### ISSUE TITLE
Can this support finding Library Text Style in another Sketch file?

### ISSUE THREAD

**Issue by pizzayap** [sonburn/shared-style-finder#3]

**Comment by pizzayap** [comment]
Hi,

In the new Sketch have the features of using Text Styles from a library.

I'm trying to use this plugin and found out it only can look for local text style and not library text style.

Any update soon to support this?

**Comment by sonburn** [comment]
@pizza0502 thank you for inquiring. I _finally_ got around to adding support for library styles. Please check out version 1.0 and let me know what you think!
